---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: awx-demo

resources:
  - github.com/ansible/awx-operator/config/default?ref=2.9.0

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.9.0
